import type { Kysely } from 'kysely';
import { promises as fs } from 'node:fs';
import { parse, relative, resolve, sep } from 'node:path';
import { performance } from 'node:perf_hooks';
import type { DatabaseMetadata } from '../../introspector';
import { DEFAULT_CJS_OUT_FILE, DEFAULT_OUT_FILE } from '../constants';
import type { GeneratorDialect } from '../dialect';
import type { Logger } from '../logger/logger';
import { type Overrides } from '../transformer/transformer';
import { DiffChecker } from './diff-checker';
import type { RuntimeEnumsStyle } from './runtime-enums-style';
import type { Serializer } from './serializer';
import { TypeScriptSerializer } from './serializer';

export type GenerateOptions = {
  camelCase?: boolean;
  customImports?: Record<string, string>;
  db: Kysely<any>;
  defaultSchemas?: string[];
  dialect: GeneratorDialect;
  excludePattern?: string | null;
  includePattern?: string | null;
  logger?: Logger;
  outFile?: string | null;
  overrides?: Overrides;
  partitions?: boolean;
  print?: boolean;
  runtimeEnums?: boolean | RuntimeEnumsStyle;
  serializer?: Serializer;
  singularize?: boolean | Record<string, string>;
  skipAutogeneratedFileComment?: boolean;
  typeMapping?: Record<string, string>;
  typeOnlyImports?: boolean;
  verify?: boolean;
};

export type SerializeFromMetadataOptions = Omit<
  GenerateOptions,
  | 'db'
  | 'excludePattern'
  | 'includePattern'
  | 'outFile'
  | 'partitions'
  | 'print'
  | 'verify'
> & {
  metadata: DatabaseMetadata;
  startTime?: number;
};

export const generate = async (options: GenerateOptions) => {
  const startTime = performance.now();

  options.logger?.info('Introspecting database...');

  const metadata = await options.dialect.introspector.introspect({
    db: options.db,
    excludePattern: options.excludePattern,
    includePattern: options.includePattern,
    partitions: options.partitions,
  });

  const newOutput = serializeFromMetadata({ ...options, metadata, startTime });

  const configuredOutFile = options.outFile;
  const isDefaultOutFile = configuredOutFile === undefined;
  const outFile =
    configuredOutFile === undefined
      ? DEFAULT_OUT_FILE
      : configuredOutFile === null
        ? null
        : resolve(process.cwd(), configuredOutFile);

  if (options.print) {
    console.info();
    console.info(newOutput);
  } else if (outFile) {
    const outputFiles =
      isDefaultOutFile
        ? [DEFAULT_OUT_FILE, DEFAULT_CJS_OUT_FILE]
        : [outFile];

    if (options.verify) {
      const diffChecker = new DiffChecker();
      let diff: string | undefined;

      for (const outputFile of outputFiles) {
        const oldOutput = await fs.readFile(outputFile, 'utf8');
        diff = diffChecker.diff(oldOutput, newOutput);
        if (diff) break;
      }

      if (diff) {
        options.logger?.error(diff);
        throw new Error(
          "Generated types are not up-to-date! Use '--log-level=error' option to view the diff.",
        );
      }

      const endTime = performance.now();
      const duration = Math.round(endTime - startTime);

      options.logger?.success(
        `Generated types are up-to-date! (${duration}ms)`,
      );
    } else {
      const outDir = parse(outFile).dir;

      await fs.mkdir(outDir, { recursive: true });
      await Promise.all(
        outputFiles.map((outputFile) => fs.writeFile(outputFile, newOutput)),
      );

      const endTime = performance.now();
      const duration = Math.round(endTime - startTime);
      const tableCount = metadata.tables.length;
      const s = tableCount === 1 ? '' : 's';
      const relativePath = `.${sep}${relative(process.cwd(), outFile)}`;

      options.logger?.success(
        `Introspected ${tableCount} table${s} and generated ${relativePath} in ${duration}ms.\n`,
      );
    }
  } else {
    options.logger?.success('No output file specified. Skipping file write.');
  }

  return newOutput;
};

export const serializeFromMetadata = (
  options: SerializeFromMetadataOptions,
) => {
  options.logger?.debug();

  const s = options.metadata.tables.length === 1 ? '' : 's';
  options.logger?.debug(
    `Found ${options.metadata.tables.length} public table${s}:`,
  );

  for (const table of options.metadata.tables) {
    options.logger?.debug(` - ${table.name}`);
  }

  options.logger?.debug();

  const serializer =
    options.serializer ??
    new TypeScriptSerializer({
      runtimeEnums: options.runtimeEnums,
      singularize: options.singularize,
      skipAutogeneratedFileComment: options.skipAutogeneratedFileComment,
      typeOnlyImports: options.typeOnlyImports,
    });

  return serializer.serializeFile(options.metadata, options.dialect, {
    camelCase: options.camelCase,
    customImports: options.customImports,
    defaultSchemas: options.defaultSchemas,
    overrides: options.overrides,
    typeMapping: options.typeMapping,
  });
};
